### ISSUE TITLE
adbinfo crash on windows 10

### ISSUE THREAD

**Issue by optak** [bexelbie/vagrant-adbinfo#81] opened 2016-01-28 14:49 UTC
```
cdk@DESKTOP-NPJE10U ~/cdk/components/rhel/rhel-docker-eclipse
$ vagrant status
Current machine states:

default                   running (virtualbox)

The VM is running. To stop this VM, you can run `vagrant halt` to
shut it down forcefully, or you can run `vagrant suspend` to simply
suspend the virtual machine. In either case, to restart it again,
simply run `vagrant up`.

cdk@DESKTOP-NPJE10U ~/cdk/components/rhel/rhel-docker-eclipse
$ vagrant plugin list
vagrant-adbinfo (0.1.0)
vagrant-registration (1.2.0)
vagrant-share (1.1.5, system)

cdk@DESKTOP-NPJE10U ~/cdk/components/rhel/rhel-docker-eclipse
$ vagrant adbinfo
C:/Users/cdk/.vagrant.d/gems/gems/vagrant-adbinfo-0.1.0/lib/command.rb:55:in ``': No such file or directory - pscp -r -P 2222 -pw vagrant -p vagrant@127.0.0.1:/home/vagrant/.docker C:/cygwin64/home/cdk/cdk/components/rhel/rhel-docker-eclipse/.vagrant/machines/default/virtualbox (Errno::ENOENT)
        from C:/Users/cdk/.vagrant.d/gems/gems/vagrant-adbinfo-0.1.0/lib/command.rb:55:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
        from C:/Users/cdk/.vagrant.d/gems/gems/vagrant-adbinfo-0.1.0/lib/command.rb:14:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'


```

The same happen with Vagrantfile from "vagrant init cdkv2"

**Comment by navidshaikh** [comment] 2016-01-30 15:02
@optak : is `pscp` installed on the system?

**Comment by optak** [comment] 2016-02-01 09:13
@navidshaikh No, pscp is not installed on windows system. I found no info about this neither in documentation, nor in vagrant-adbinfo-README.md
I tried to install it by "apt-cyg install pscp" but nothing is available, can you please tell me from where can I install pscp?

**Comment by navidshaikh** [comment] 2016-02-01 10:38
@optak : You can download the pscp utility from http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html

**Comment by optak** [comment] 2016-02-01 10:53
@navidshaikh : thanks, it solved the problem, if I have pscp.exe in PATH, adbinfo works on win10. So now it's only documentation issue, I'll write a note about it to our pad.
But I don't understand why this happened. Adbinfo didn't need this binary in previous versions and on RHEL-7 I have the same version of plugin, but pscp is not needed.

**Comment by LalatenduMohanty** [comment] 2016-02-03 09:57
This looks a duplicate of https://github.com/projectatomic/vagrant-adbinfo/issues/51

**Closed as completed by LalatenduMohanty** 2016-02-03 09:57 UTC
Labels: bug, documentation
